### ISSUE TITLE
redmine3系でファイルアップロードでエラーになる

### ISSUE THREAD

**Issue by agilemasayuki** [agileware-jp/redmine_importer#10]
対応するかどうかは任せます。

以下ログです。

NoMethodError (undefined method `find_or_create_by_user_id' for #<Class:0x007f9c9a3ddd10>):
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.1/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
  plugins/redmine_importer/app/controllers/importer_controller.rb:33:in `match'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/abstract_controller/base.rb:198:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'

**Comment by agilemasayuki** [comment]
追記
https://github.com/stateio/redmine_importer
では3.0.3で動いてました。
